### ISSUE TITLE
create a table-of-content component

### ISSUE THREAD

**Issue by hakilebara** [ember-learn/ember-styleguide#141] opened 2019-02-06 15:51 UTC
The following ember-learn apps:
* guides
* deprecations
* api

use their own table of content component. I suggest moving this component to a single implementation in the styleguide.

**Note**: The current implementations of table-of-content use http://embermap.github.io/ember-collapsible-panel

**Comment by MelSumner** [comment] 2019-02-06 17:45
Thank you for writing this issue! I believe this is a duplicate of issue #99 though.

**Closed by MelSumner** 2019-02-06 17:45 UTC
